on:
  push:
    branches:
      - main

name: Build Sumocli

jobs:
  create_github_release:
    name: Create GitHub Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.4
        with:
          versionSpec: '5.2.x'
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.4
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "${{ steps.gitversion.outputs.majorMinorPatch }}"



