on:
  push:
    branches:
      - main

name: Build Sumocli

jobs:
  create_github_release:
    name: Create GitHub Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Install Golang



