name: Sumocli Tests

on: [pull_request, push]

env:
  GOVERSION: '1.17.6'

jobs:
  compile_linux_binary:
    name: Test and Compile Linux Binary
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go Environment
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVERSION }}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Sumocli
        run: go build ./cmd/sumocli
      - name: Run Tests
        run: go test ./...

  compile_macos_binary:
    name: Test and Compile macOS Binary
    runs-on: macos-latest
    steps:
      - name: Setup Go Environment
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVERSION }}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Sumocli
        run: go build ./cmd/sumocli
      - name: Run Tests
        run: go test ./...

  compile_windows_binary:
    name: Test and Compile Windows Binary
    runs-on: windows-latest
    steps:
      - name: Setup Go Environment
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVERSION }}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Sumocli
        run: go build ./cmd/sumocli
      - name: Run Tests
        run: go test ./...
