name: Sumocli Build and Release

on: push

# on:
#  pull_request:
#    types: closed
#    branches:
#      - main

jobs:
  create_semver:
    name: Create Version
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag
        id: semvertag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
          release_strategy: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      semvertag: ${{ steps.semvertag.outputs.tag }}
      
  build_windows:
    name: Build Windows Binary
    needs: create_semver
    runs-on: windows-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.x'
      - name: Install AzureSignTool
        shell: pwsh
        run: dotnet tool install --global AzureSignTool --version 2.0.17
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Dependencies
        run: go mod download
      - name: Build Sumocli
        shell: pwsh
        run: |
          $build = $Env:GITHUB_RUN_NUMBER
          $time = Get-Date
          go build -ldflags `
            "-X 'github.com/wizedkyle/sumocli/internal/build.Version=${{ needs.create_semver.outputs.semvertag }}' `
            -X 'github.com/wizedkyle/sumocli/internal/build.Build=$build' `
            -X 'github.com/wizedkyle/sumocli/internal/build.Date=$time'" `
            ./cmd/sumocli
      - name: Signing Executable
        shell: pwsh
        run: |
          azuresigntool sign --description-url "https://sumocli.gitbook.io" --file-digest sha256 `
            --azure-key-vault-url ${{ secrets.AZURE_KEY_VAULT_URL }} `
            --azure-key-vault-client-id ${{ secrets.AZURE_KEY_VAULT_CLIENT_ID }} `
            --azure-key-vault-client-secret ${{ secrets.AZURE_KEY_VAULT_CLIENT_SECRET }} `
            --azure-key-vault-certificate ${{ secrets.AZURE_KEY_VAULT_CERTIFICATE }} `
            --timestamp-rfc3161 http://timestamp.sectigo.com `
            --timestamp-digest sha256 `
            sumocli.exe
      - name: Upload Windows Binary
        uses: actions/upload-artifact@v2
        with:
          name: sumocli_windows_amd64
          path: sumocli.exe

  build_linux:
    name: Build Linux Binary
    needs: create_semver
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Dependencies
        run: go mod download
      - name: Build Sumocli
        shell: pwsh
        run: |
          $build = $Env:GITHUB_RUN_NUMBER
          $time = Get-Date
          go build -ldflags `
            "-X 'github.com/wizedkyle/sumocli/internal/build.Version=${{ needs.create_semver.outputs.semvertag }}' `
            -X 'github.com/wizedkyle/sumocli/internal/build.Build=$build' `
            -X 'github.com/wizedkyle/sumocli/internal/build.Date=$time'" `
            ./cmd/sumocli
      - name: Upload Windows Binary
        uses: actions/upload-artifact@v2
        with:
          name: sumocli_linux_amd64
          path: sumocli

#  create_github_release:
#    name: Create GitHub Release
#    needs: create_semver
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Repo
#        uses: actions/checkout@v2
#      - name: Create Release
#        id: createrelease
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ needs.create_semver.outputs.semvertag }}
