name: Sumocli Build and Release

on:
  pull_request:
    types: closed
    branches:
      - main

jobs:
  create_semver:
    name: Create Version
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag
        id: semvertag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
          release_strategy: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      semvertag: ${{ steps.semvertag.outputs.tag }}

  create_github_release:
    name: Create GitHub Release
    needs: create_semver
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.create_semver.outputs.semvertag }}
          release_name: Release ${{ needs.create_semver.outputs.semvertag }}
          draft: false
          prerelease: false
    outputs:
      releaseurl: ${{ steps.create_release.outputs.upload_url }}

  build_windows:
    name: Build Windows Binary
    needs: [create_semver, create_github_release]
    runs-on: windows-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.x'
      - name: Install AzureSignTool
        shell: pwsh
        run: dotnet tool install --global AzureSignTool --version 2.0.17
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Dependencies
        run: go mod download
      - name: Build Sumocli
        shell: pwsh
        run: |
          $build = $Env:GITHUB_RUN_NUMBER
          $time = Get-Date
          go build -ldflags `
            "-X 'github.com/wizedkyle/sumocli/internal/build.Version=${{ needs.create_semver.outputs.semvertag }}' `
            -X 'github.com/wizedkyle/sumocli/internal/build.Build=$build' `
            -X 'github.com/wizedkyle/sumocli/internal/build.Date=$time'" `
            ./cmd/sumocli
      - name: Signing Executable
        shell: pwsh
        run: |
          azuresigntool sign --description-url "https://sumocli.gitbook.io" --file-digest sha256 `
            --azure-key-vault-url ${{ secrets.AZURE_KEY_VAULT_URL }} `
            --azure-key-vault-client-id ${{ secrets.AZURE_KEY_VAULT_CLIENT_ID }} `
            --azure-key-vault-client-secret ${{ secrets.AZURE_KEY_VAULT_CLIENT_SECRET }} `
            --azure-key-vault-certificate ${{ secrets.AZURE_KEY_VAULT_CERTIFICATE }} `
            --timestamp-rfc3161 http://timestamp.sectigo.com `
            --timestamp-digest sha256 `
            sumocli.exe
      - name: Zip Release
        shell: pwsh
        run: |
          Compress-Archive -Path sumocli.exe -DestinationPath sumocli-windows-amd64.zip
      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_github_release.outputs.releaseurl }}
          asset_path: ./sumocli-windows-amd64.zip
          asset_name: sumocli-windows-amd64.zip
          asset_content_type: application/zip

  build_linux:
    name: Build Linux Binary
    needs: [create_semver, create_github_release]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Dependencies
        run: go mod download
      - name: Build Sumocli
        shell: pwsh
        run: |
          $build = $Env:GITHUB_RUN_NUMBER
          $time = Get-Date
          go build -ldflags `
            "-X 'github.com/wizedkyle/sumocli/internal/build.Version=${{ needs.create_semver.outputs.semvertag }}' `
            -X 'github.com/wizedkyle/sumocli/internal/build.Build=$build' `
            -X 'github.com/wizedkyle/sumocli/internal/build.Date=$time'" `
            ./cmd/sumocli
      - name: Zip Releases
        run: |
          zip -r sumocli-linux-amd64.zip sumocli
      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_github_release.outputs.releaseurl }}
          asset_path: ./sumocli-linux-amd64.zip
          asset_name: sumocli-linux-amd64.zip
          asset_content_type: application/zip

  build_macos_intel:
    name: Build macOS Binary (Intel)
    needs: [create_semver, create_github_release]
    runs-on: macos-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Dependencies
        run: go mod download
      - name: Build Sumocli
        shell: pwsh
        run: |
          $build = $Env:GITHUB_RUN_NUMBER
          $time = Get-Date
          go build -ldflags `
            "-X 'github.com/wizedkyle/sumocli/internal/build.Version=${{ needs.create_semver.outputs.semvertag }}' `
            -X 'github.com/wizedkyle/sumocli/internal/build.Build=$build' `
            -X 'github.com/wizedkyle/sumocli/internal/build.Date=$time'" `
            ./cmd/sumocli
      - name: Zip Releases
        run: |
          zip -r sumocli-macos-amd64.zip sumocli
      - name: Upload macOS Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_github_release.outputs.releaseurl }}
          asset_path: ./sumocli-macos-amd64.zip
          asset_name: sumocli-macos-amd64.zip
          asset_content_type: application/zip

  build_macos_apple_silicon:
    name: Build macOS Binary (Apple Silicon)
    needs: [create_semver, create_github_release]
    runs-on: macos-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Dependencies
        run: go mod download
      - name: Build Sumocli
        shell: pwsh
        run: |
          $build = $Env:GITHUB_RUN_NUMBER
          $time = Get-Date
          go build GOOS=darwin GOARCH=arm64 -ldflags `
            "-X 'github.com/wizedkyle/sumocli/internal/build.Version=${{ needs.create_semver.outputs.semvertag }}' `
            -X 'github.com/wizedkyle/sumocli/internal/build.Build=$build' `
            -X 'github.com/wizedkyle/sumocli/internal/build.Date=$time'" `
            ./cmd/sumocli
      - name: Zip Releases
        run: |
          zip -r sumocli-macos-arm64.zip sumocli
      - name: Upload macOS Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_github_release.outputs.releaseurl }}
          asset_path: ./sumocli-macos-arm64.zip
          asset_name: sumocli-macos-arm64.zip
          asset_content_type: application/zip
