on:
  pull_request:
    types: closed
    branches: 
      - main

jobs:
  create_semver:
    name: Create Version
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag
        id: semvertag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
          release_strategy: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      semvertag: ${{ steps.semvertag.outputs.tag }}
      
  compile_windows:
    name: Compile Windows Binary
    needs: create_semver
    runs-on: windows-latest
    env:
      GOPATH: ${{ github.workspace }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}
      - name: Install Go Environment
        uses: actions/setup-go@v2
        with:
          go_version: '1.15.2'
      - name: Build Go Application
        shell: pwsh
        run: |
          $build = $Env:GITHUB_RUN_NUMBER
          $time = Get-Date
          Write-Host $Env:GOPATH
          go build -ldflags="-X 'github.com/wizedkyle/sumocli/version.Version=${{ needs.create_semver.outputs.semvertag }}' -X 'github.com/wizedkyle/sumocli/version.Build=$build' -X 'github.com/wizedkyle/sumocli/version.Time=$time'"
      - name: Upload Windows Binary
        uses: actions/upload-artifact@v2
        with:
          name: sumocli-windows
          path: sumocli.exe
          
  compile_macos:
    name: Compile macOS Binary
    needs: create_semver
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Go Environment
        uses: actions/setup-go@v2
        with:
          go_version: '1.15.2'
      - name: Build Go Application
        shell: pwsh
        run: |
          $build = $Env:GITHUB_RUN_NUMBER
          $time = Get-Date
          go build -ldflags="-X 'github.com/wizedkyle/sumocli/version.Version=${{ needs.create_semver.outputs.semvertag }}' -X 'github.com/wizedkyle/sumocli/version.Build=$build' -X 'github.com/wizedkyle/sumocli/version.Time=$time'"
      - name: Upload macOS Binary
        uses: actions/upload-artifact@v2
        with:
          name: sumocli-macos
          path: sumocli

  create_github_release:
    name: Create GitHub Release
    needs: create_semver
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Create Release
        id: createrelease
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.create_semver.outputs.semvertag }}
